version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "bot"
    commit-message:
      prefix: "chore(deps)"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
    versioning-strategy: "auto"
